config/routes.rb
Rails.application.routes.draw do
  
  match '/sitemap', to: 'pages#sitemap', via: 'get'

  get '/index.html', to: redirect('/')
  get '/reservations.html', to: redirect('/book-online')
  get '/bar.html', to: redirect('/restaurant')
  get '/gallery.html', to: redirect('/gallery')
  get '/heroes.html', to: redirect('/restaurant')
  resources :testimonials
  root 'pages#home'

  get '/about'                   => 'pages#about'

  get  '/contact-us'             => 'enquiries#new'
  post '/contact-us'             => 'enquiries#create'
  get  '/contact-us/thanks'      => 'enquiries#thanks'

  get  '/book-online'             => 'bookings#new'
  post '/book-online'             => 'bookings#create'
  get  '/book-online/thanks'      => 'bookings#thanks'

  get     'login'     => 'user_system/sessions#new'
  post    'login'     => 'user_system/sessions#create'
  delete  'logout'    => 'user_system/sessions#destroy'

  namespace :admin do
    resources :pages, except: :show do
      collection { get :pdf_menu }
      resources :banner_image, only: :destroy
    end
    resources :enquiries, only: [:index, :destroy, :show]
    resources :bookings, only: [:index, :destroy, :show]
    resources :events, except: :show
    resources :gallery_images, except: :show do
      collection { post :upload }
    end
  end

  scope module: :user_system do
    resources :users, only: [:new, :create, :edit, :update, :show]
    resources :sessions, only: [:new, :create, :destroy]
    resources :account_activations, only: :edit
    resources :password_resets, only: [:new, :create, :edit, :update]
  end

  mount Ckeditor::Engine => '/ckeditor'

  resources :events, only: :index
  resources :bookings, only: [:create, :new]
  resources :gallery_images, path: 'gallery', only: [:index]
  resources :enquiries, only: [:create, :new]
  resources :pages, path: '', only: :show




end

app/models/event.rb
class Event < ApplicationRecord

  default_scope -> { order created_at: :desc }
  mount_uploader :banner, ImageUploader
  mount_uploader :attachment, FileUploader

end

app/controllers/admin/events_controller.rb
class Admin::EventsController < AdminController

  def index
    @events = Event.all
  end

  def new
    @event = Event.new
  end

  def edit
    @event = Event.find(params[:id])
  end

  def create
    @event = Event.new(event_params)

    if @event.save
      redirect_to events_path
    else
      render :new
    end
  end

  def update
    @event = Event.find(params[:id])
    if @event.update(event_params)
      redirect_to events_path
    else
      render :edit
    end
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    redirect_to admin_events_url
  end

  private

    def event_params
      params.require(:event).permit(:name, :banner, :body, :attachment)
    end
  

end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  def index
    @page = Page.find_by(machine_name: 'whats_on_events')
    @events = Event.all
    @booking = Booking.event.new
  end

end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/admin/events/_form.html.haml
= form_for [:admin, @event] do |f|

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :body
    = f.cktext_area :body
  = field_set_tag 'Image' do
    - unless @event.new_record? || @event.banner.blank?
      = image_tag @event.banner.featured
    .field
      = f.label :banner
      = f. file_field :banner

  = field_set_tag 'Attachment' do
    - unless @event.new_record? || @event.attachment.blank?
      = @event.attachment.url.split('/').last rescue ''
    .field
      = f.label :attachment
      = f. file_field :attachment
  .actions
    = f.submit

app/views/admin/events/_navigation_bar.html.haml
= link_to 'New Event', new_admin_event_path

app/views/admin/events/edit.html.haml
- provide :title, 'Edit Event'
= render 'form'

app/views/admin/events/index.html.haml
- provide :title, 'Events'
%table
  %thead
    %tr
      %th Name
      %th Actions
  %tbody
    - @events.each do |event|
      %tr
        %td= event.name
        %td.action_columns
          = link_to 'Edit', edit_admin_event_path(event)
          = link_to 'Delete', [:admin, event], method: :delete, data: { confirm: 'Are you sure?' }

app/views/admin/events/new.html.haml
- provide :title, 'New Event'
= render 'form'