config/routes.rb
Rails.application.routes.draw do
  
  match '/sitemap', to: 'pages#sitemap', via: 'get'

  get '/index.html', to: redirect('/')
  get '/reservations.html', to: redirect('/book-online')
  get '/bar.html', to: redirect('/restaurant')
  get '/gallery.html', to: redirect('/gallery')
  get '/heroes.html', to: redirect('/restaurant')
  resources :testimonials
  root 'pages#home'

  get '/about'                   => 'pages#about'

  get  '/contact-us'             => 'enquiries#new'
  post '/contact-us'             => 'enquiries#create'
  get  '/contact-us/thanks'      => 'enquiries#thanks'

  get  '/book-online'             => 'bookings#new'
  post '/book-online'             => 'bookings#create'
  get  '/book-online/thanks'      => 'bookings#thanks'

  get     'login'     => 'user_system/sessions#new'
  post    'login'     => 'user_system/sessions#create'
  delete  'logout'    => 'user_system/sessions#destroy'

  namespace :admin do
    resources :pages, except: :show do
      collection { get :pdf_menu }
      resources :banner_image, only: :destroy
    end
    resources :enquiries, only: [:index, :destroy, :show]
    resources :bookings, only: [:index, :destroy, :show]
    resources :events, except: :show
    resources :gallery_images, except: :show do
      collection { post :upload }
    end
  end

  scope module: :user_system do
    resources :users, only: [:new, :create, :edit, :update, :show]
    resources :sessions, only: [:new, :create, :destroy]
    resources :account_activations, only: :edit
    resources :password_resets, only: [:new, :create, :edit, :update]
  end

  mount Ckeditor::Engine => '/ckeditor'

  resources :events, only: :index
  resources :bookings, only: [:create, :new]
  resources :gallery_images, path: 'gallery', only: [:index]
  resources :enquiries, only: [:create, :new]
  resources :pages, path: '', only: :show




end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/banner_image.rb
class BannerImage < ApplicationRecord

  mount_uploader :image, ImageUploader

end

app/models/booking.rb
class Booking < ApplicationRecord
  validates :name, :email, presence: true

  enum booking_type: [:table, :event]

end

app/models/enquiry.rb
class Enquiry < ApplicationRecord

  # validate :reject_if_casino_or_drugs

  # def reject_if_casino_or_drugs
  #   if message =~ /(casino)|(slots)|(viagra)|(nigeria)|(http)|(bit\.ly)|(www\.)|(we are not spammers)|(SEO)|(captcha)|(\<a)|(href)|(\p{Han})|(\p{Cyrillic}+)|(Unsubscribe)|(opt-out)/
  #     errors.add(:comment, 'is spam or written by robot or generally unrelated')
  #   end
  # end
end

app/models/event.rb
class Event < ApplicationRecord

  default_scope -> { order created_at: :desc }
  mount_uploader :banner, ImageUploader
  mount_uploader :attachment, FileUploader

end

app/models/gallery_image.rb
class GalleryImage < ApplicationRecord

  attr_accessor :tags

  mount_uploader :image, GalleryUploader

  has_many :gallery_tags
  has_many :tags, through: :gallery_tags

end

app/models/gallery_tag.rb
class GalleryTag < ApplicationRecord

  belongs_to :gallery_image
  belongs_to :tag

end

app/models/page.rb
class Page < ApplicationRecord

  attr_accessor :images, :gallery_tags

  has_many :banner_images

  scope :menu, -> { order(order: :asc).where(include_in_menu: true) }
  scope :featured, -> { where(featured: true) }
  scope :regular_page, -> { all }
  scope :menu_page, -> { where(menu: true).order(order: :asc) }

  enum sidebar: [:gallery, :in_menu]

  extend FriendlyId
  friendly_id :name, use: :slugged

  has_many :page_tags
  has_many :tags, through: :page_tags
  has_many :gallery_images, through: :tags

  mount_uploader :pdf, FileUploader

end

app/models/page_tag.rb
class PageTag < ApplicationRecord

  belongs_to :page
  belongs_to :tag

end

app/models/tag.rb
class Tag < ApplicationRecord

  has_many :gallery_tags
  has_many :gallery_images, through: :gallery_tags

end

app/models/testimonial.rb
class Testimonial < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord

  attr_accessor :remember_token, :activation_token, :reset_token
  before_save { self.email = email.downcase }
  before_create :create_activation_digest
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
  validates :password, length: { minimum: 6 }, allow_nil: true
  has_secure_password

  def User.new_token
    SecureRandom.urlsafe_base64
  end

  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
        BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # Forgets a user.
  def forget
    update_attribute(:remember_digest, nil)
  end

  # Returns true if the given token matches the digest.
  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

  # Activates an account.
  def activate
    update_attribute(:activated,    true)
    update_attribute(:activated_at, Time.zone.now)
  end

  # Sends activation email.
  def send_activation_email
    UserMailer.account_activation(self).deliver_now
  end

  # Sets the password reset attributes.
  def create_reset_digest
    self.reset_token = User.new_token
    update_attribute(:reset_digest,  User.digest(reset_token))
    update_attribute(:reset_sent_at, Time.zone.now)
  end

  # Sends password reset email.
  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end

  # Returns true if a password reset has expired.
  def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end

  private

  def create_activation_digest
    self.activation_token  = User.new_token
    self.activation_digest = User.digest(activation_token)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper

  def page_title title
    if title.blank?
      'Ringland Swan'
    else
      title
    end
  end

end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/enquiries_helper.rb
module EnquiriesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/image_helper.rb
module ImageHelper
end

app/helpers/pages_helper.rb
module PagesHelper

  def summary page
    page.summary || truncate(page.body, length: 200)
  end

  def page_banner page
    if page.banner_images.count > 1
      content_tag :div, id: :banner_wrapper do
        content_tag :div, id: 'page_slideshow' do
          slider(page) +
          content_tag(:h3, page.banner_caption || '', class: 'page_banner_caption')
        end
      end
    elsif page.banner_images.count == 1
      content_tag :div, id: :banner_wrapper do
        content_tag :div, content_tag(:h3, page.banner_caption || '', class: 'page_banner_caption'), class: :page_banner, style: "background-image: url(#{page.banner_images.first.image.banner})"
      end

    end
  end

  def slider page
    content_tag :div, id: 'slides' do
      page.banner_images.collect { |banner_image| content_tag(:div, '', class: :page_banner, style: "background-image: url(#{banner_image.image.banner})") }.join.html_safe
    end
  end

end

app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in user
    session[:user_id] = user.id 
  end

  def log_out 
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end

  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  # Returns the user corresponding to the remember token cookie.
  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(:remember, cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  def current_user? user 
    user == current_user
  end

  def signed_in?
    !current_user.nil?
  end

  def signed_in_as_admin?
    if signed_in? && current_user.admin?
      return true
    else
      return false
    end
  end

  #def grab_session_ids
  #  @user = @user ? current_user : check_domains_for_user
  #  @cart = current_cart 
  #  rescue ActiveRecord::RecordNotFound
  #    return false
  #end



end

app/helpers/testimonials_helper.rb
module TestimonialsHelper
end

app/views/admin/_admin_menu.html.haml
= link_to 'pages', admin_pages_path
= link_to 'enquiries', admin_enquiries_path
= link_to 'bookings', admin_bookings_path
= link_to 'events', admin_events_path
= link_to 'gallery', admin_gallery_images_path

app/views/admin/pages/_form.html.haml
= form_for [:admin, @page] do |f|

  #two_panel_form
    #main_panel
      .field
        = f.label :name
        = f.text_field :name
      .field
        = f.label :body
        = f.cktext_area :body
      .field
        = f.label :summary
        = f.text_area :summary
      = field_set_tag 'Banner' do
        .field
          - unless @page.new_record?
            .image_gal
              - @page.banner_images.each do |image|
                = image_tag image.image.featured
                = link_to 'Delete', [:admin, @page, image], method: :delete, data: {confirm: 'Are you sure?'}

          = f.label :images
          = f.file_field :images, multiple: true
        .field
          = f.label :banner_caption
          = f.text_field :banner_caption
    #side_panel
      .field
        = f.label :menu_name
        = f.text_field :menu_name
      .field
        = f.label :page_title
        = f.text_field :page_title
      .field
        = f.label :meta_description
        = f.text_area :meta_description
      .field
        = f.label :include_in_menu
        = f.check_box :include_in_menu
      .field
        = f.label :featured
        = f.check_box :featured
      .field
        = f.label :menu, "This is a menu"
        = f.check_box :menu
      .field
        = f.label :gallery_tags, "Show images on this page with the following tags (Separate with commas)"
        = f.text_field :gallery_tags
      .field
        = f.label :order
        = f.text_field :order

  .actions
    = f.submit

app/views/admin/pages/_navigation_bar.html.haml
= link_to 'New Page', new_admin_page_path
= link_to 'New PDF Menu', pdf_menu_admin_pages_path

app/views/admin/pages/edit.html.haml
- provide :title, 'Edit Page'
= render 'form'

app/views/admin/pages/index.html.haml
- provide :title, 'Pages'
%table
  %thead
    %tr
      %th Name
      %th Tags
      %th Actions
  %tbody
    - @pages.each do |page|
      %tr
        %td= page.name
        %td= page.tags.collect{|t| t.tag}.join(', ')
        %td.action_columns
          = link_to 'Show', page
          = link_to 'Edit', edit_admin_page_path(page)
          = link_to 'Delete', [:admin, page], method: :delete, data: { confirm: 'Are you sure?' }

app/views/admin/pages/new.html.haml
- provide :title, 'New Page'
= render 'form'

app/views/admin/pages/pdf_menu.html.haml
- provide :title, 'New PDF Menu'
= form_for [:admin, @page] do |f|

  #two_panel_form
    #main_panel
      .field
        = f.label :name
        = f.text_field :name
      .field
        = f.label :page_title
        = f.text_field :page_title
      .field
        = f.label :meta_description
        = f.text_area :meta_description
      .field
        = f.label :pdf, 'Menu PDF'
        = f.file_field :pdf
      .field.hidden
        = f.check_box :menu, checked: true
        = f.check_box :display_as_pdf, checked: true


      .field
        = f.label :order
        = f.text_field :order


  .actions
    = f.submit