config/routes.rb
Rails.application.routes.draw do
  
  match '/sitemap', to: 'pages#sitemap', via: 'get'

  get '/index.html', to: redirect('/')
  get '/reservations.html', to: redirect('/book-online')
  get '/bar.html', to: redirect('/restaurant')
  get '/gallery.html', to: redirect('/gallery')
  get '/heroes.html', to: redirect('/restaurant')
  resources :testimonials
  root 'pages#home'

  get '/about'                   => 'pages#about'

  get  '/contact-us'             => 'enquiries#new'
  post '/contact-us'             => 'enquiries#create'
  get  '/contact-us/thanks'      => 'enquiries#thanks'

  get  '/book-online'             => 'bookings#new'
  post '/book-online'             => 'bookings#create'
  get  '/book-online/thanks'      => 'bookings#thanks'

  get     'login'     => 'user_system/sessions#new'
  post    'login'     => 'user_system/sessions#create'
  delete  'logout'    => 'user_system/sessions#destroy'

  namespace :admin do
    resources :pages, except: :show do
      collection { get :pdf_menu }
      resources :banner_image, only: :destroy
    end
    resources :enquiries, only: [:index, :destroy, :show]
    resources :bookings, only: [:index, :destroy, :show]
    resources :events, except: :show
    resources :gallery_images, except: :show do
      collection { post :upload }
    end
  end

  scope module: :user_system do
    resources :users, only: [:new, :create, :edit, :update, :show]
    resources :sessions, only: [:new, :create, :destroy]
    resources :account_activations, only: :edit
    resources :password_resets, only: [:new, :create, :edit, :update]
  end

  mount Ckeditor::Engine => '/ckeditor'

  resources :events, only: :index
  resources :bookings, only: [:create, :new]
  resources :gallery_images, path: 'gallery', only: [:index]
  resources :enquiries, only: [:create, :new]
  resources :pages, path: '', only: :show




end

app/models/testimonial.rb
class Testimonial < ApplicationRecord
end

app/controllers/testimonials_controller.rb
class TestimonialsController < ApplicationController
  before_action :set_testimonial, only: [:show, :edit, :update, :destroy]

  # GET /testimonials
  def index
    @testimonials = Testimonial.all
  end

  # GET /testimonials/1
  def show
  end

  # GET /testimonials/new
  def new
    @testimonial = Testimonial.new
  end

  # GET /testimonials/1/edit
  def edit
  end

  # POST /testimonials
  def create
    @testimonial = Testimonial.new(testimonial_params)

    if @testimonial.save
      redirect_to @testimonial, notice: 'Testimonial was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /testimonials/1
  def update
    if @testimonial.update(testimonial_params)
      redirect_to @testimonial, notice: 'Testimonial was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /testimonials/1
  def destroy
    @testimonial.destroy
    redirect_to testimonials_url, notice: 'Testimonial was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_testimonial
      @testimonial = Testimonial.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def testimonial_params
      params.require(:testimonial).permit(:name, :body, :author)
    end
end

app/helpers/testimonials_helper.rb
module TestimonialsHelper
end

app/views/testimonials/_form.html.haml
= form_for @testimonial do |f|
  - if @testimonial.errors.any?
    #error_explanation
      %h2= "#{pluralize(@testimonial.errors.count, "error")} prohibited this testimonial from being saved:"
      %ul
        - @testimonial.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :body
    = f.text_area :body
  .field
    = f.label :author
    = f.text_field :author
  .actions
    = f.submit 'Save'

app/views/testimonials/edit.html.haml
%h1 Editing testimonial

= render 'form'

= link_to 'Show', @testimonial
\|
= link_to 'Back', testimonials_path

app/views/testimonials/index.html.haml
%h1 Listing testimonials

%table
  %thead
    %tr
      %th Name
      %th Body
      %th Author
      %th
      %th
      %th

  %tbody
    - @testimonials.each do |testimonial|
      %tr
        %td= testimonial.name
        %td= testimonial.body
        %td= testimonial.author
        %td= link_to 'Show', testimonial
        %td= link_to 'Edit', edit_testimonial_path(testimonial)
        %td= link_to 'Destroy', testimonial, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Testimonial', new_testimonial_path

app/views/testimonials/new.html.haml
%h1 New testimonial

= render 'form'

= link_to 'Back', testimonials_path

app/views/testimonials/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @testimonial.name
%p
  %b Body:
  = @testimonial.body
%p
  %b Author:
  = @testimonial.author

= link_to 'Edit', edit_testimonial_path(@testimonial)
\|
= link_to 'Back', testimonials_path